package com.jlife.abon.report;

/**
 * @author Dzmitry Misiuk
 */
public enum ReportKey {

    ORDER_NUMBER,
    PRODUCT_NAME,
    COUNT_OF_SOLD,
    ALL_INITIAL_ATTENDANCES,
    ALL_AVAILABLE_ATTENDANCES,
    PRODUCT_COMMON_PRICE,
    INITIAL_PRICE,
    INITIALS,
    CARD_UUID,
    PHONE,
    CREATED_DATE,
    LAST_ATTENDANCE_DATE,
    START_DATE,
    END_DATE,
    PURCHASE_DATE,
    DATE_TIME,
    COUNT_OF_ACTUAL,
    BIRTHDAY,
    AGE,
    EMAIL,
    DATE,
    COUNT_SINGLE_ATTENDANCES,
    COUNT_ATTENDANCES,
    SINGLE_ATTENDANCES_COMMON_PRICE,
    LAST_NAME, NAME, INTERNAL_NUMBER, DISCOUNT

}
